repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    # Issue on Github action CI?
    # -   id: no-commit-to-branch
    #     args: [--branch, main]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [--profile, black]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.2
  hooks:
    - id: pyupgrade
      args: [--py38-plus]
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
   - id: flake8
     args: ['--ignore=E501,E203,E731,W503']
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      additional_dependencies: [click==8.0.2]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.990
  hooks:
    - id: mypy
      additional_dependencies: [types-dataclasses, numpy==1.22.4]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v15.0.7'
  hooks:
  - id: clang-format
    # Not formatting external dependencies.
    files: tessellate/tile/
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.3
  hooks:
    - id: nbqa-black
    - id: nbqa-pyupgrade
      args: [--py37-plus]
    - id: nbqa-isort
      args: ['--profile=black']
    - id: nbqa-flake8
      args: ['--ignore=E501,E203,E302,E402,E731,W503']
- repo: local
  hooks:
  - id: copyright-header-check-module
    name: copyright-header-check-module
    entry: python3 -m examples_utils test_copyright --amend ./tessellate/tile/
    pass_filenames: false
    language: python
    additional_dependencies:
      - 'git+https://github.com/graphcore/examples-utils@latest_stable'
  - id: copyright-header-check-tests
    name: copyright-header-check-tests
    entry: python3 -m examples_utils test_copyright --amend ./tests
    pass_filenames: false
    language: python
    additional_dependencies:
      - 'git+https://github.com/graphcore/examples-utils@latest_stable'
